version: '3'
services:
  first-stage:
    container_name: first-stage
    image: devkitpro/devkitarm:20190212
    command: "bash -c 'cd /argon-first-stage && make clean && make'"
    volumes:
    - ./output:/output
    - ./argon-first-stage/:/argon-first-stage
